CREATE TABLE bank_name_config (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    bank_name       VARCHAR(200) NOT NULL UNIQUE,
    created_by      VARCHAR(100),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO bank_name_config (bank_name) VALUES
('Vietcombank'),
('VietinBank'),
('BIDV'),
('Agribank'),
('Techcombank'),
('MB Bank'),
('ACB'),
('VPBank'),
('HDBank'),
('Sacombank'),
('VIB'),
('TPBank'),
('SHB'),
('OCB'),
('MSB'),
('Nam A Bank'),
('PVcomBank'),
('SeABank'),
('Bac A Bank'),
('ABBANK'),
('LienVietPostBank'),
('NCB'),
('SCB'),
('KienLongBank'),
('VietCapitalBank'),
('Saigonbank'),
('PG Bank'),
('OceanBank'),
('Standard Chartered'),
('HSBC'),
('Citibank'),
('ANZ'),
('Shinhan Bank'),
('Woori Bank'),
('CIMB Bank'),
('Hong Leong Bank'),
('Public Bank'),
('UOB'),
('Maybank'),
('Bangkok Bank'),
('Bank of China'),
('DBS Bank');
